(let ((home (getenv "HOME")))
  (add-model "simpleBox.obj" :type :obj :is-base #t)
  (add-model "/share/space1/kiselgra/sportscar/out23.obj" :type :subdobj)
  (add-model "/share/space1/kiselgra/sportscar/out32.obj" :type :subdobj)
  (add-model "/share/space1/kiselgra/sportscar/out3.obj" :type :subdobj)
  (add-model "/share/space1/kiselgra/sportscar/out0.obj" :type :subdobj)
  (add-model "/share/space1/kiselgra/sportscar/out8.obj" :type :subdobj)
  (add-model "/share/space1/kiselgra/sportscar/out19.obj" :type :subdobj)
  (add-model "/share/space1/kiselgra/sportscar/out11.obj" :type :subdobj)
  (add-model "/share/space1/kiselgra/sportscar/out33.obj" :type :subdobj)
  (add-model "/share/space1/kiselgra/sportscar/out5.obj" :type :subdobj)
  (add-model "/share/space1/kiselgra/sportscar/out16.obj" :type :subdobj)
  (add-model "/share/space1/kiselgra/sportscar/out25.obj" :type :subdobj)
  (add-model "/share/space1/kiselgra/sportscar/out18.obj" :type :subdobj)
  (add-model "/share/space1/kiselgra/sportscar/out9.obj" :type :subdobj)
  (add-model "/share/space1/kiselgra/sportscar/out12.obj" :type :subdobj)
  (add-model "/share/space1/kiselgra/sportscar/out17.obj" :type :subdobj)
  (add-model "/share/space1/kiselgra/sportscar/out21.obj" :type :subdobj)
  (add-model "/share/space1/kiselgra/sportscar/out28.obj" :type :subdobj)
  (add-model "/share/space1/kiselgra/sportscar/out27.obj" :type :subdobj)
  (add-model "/share/space1/kiselgra/sportscar/out30.obj" :type :subdobj)
  (add-model "/share/space1/kiselgra/sportscar/out6.obj" :type :subdobj)
  (add-model "/share/space1/kiselgra/sportscar/out20.obj" :type :subdobj)
  (add-model "/share/space1/kiselgra/sportscar/out7.obj" :type :subdobj)
  (add-model "/share/space1/kiselgra/sportscar/out10.obj" :type :subdobj)
  (add-model "/share/space1/kiselgra/sportscar/out22.obj" :type :subdobj)
  (add-model "/share/space1/kiselgra/sportscar/out1.obj" :type :subdobj)
  (add-model "/share/space1/kiselgra/sportscar/out2.obj" :type :subdobj)
  (add-model "/share/space1/kiselgra/sportscar/out29.obj" :type :subdobj)
  (add-model "/share/space1/kiselgra/sportscar/out13.obj" :type :subdobj)
  (add-model "/share/space1/kiselgra/sportscar/out4.obj" :type :subdobj)
  (add-model "/share/space1/kiselgra/sportscar/out15.obj" :type :subdobj)
  (add-model "/share/space1/kiselgra/sportscar/out14.obj" :type :subdobj)
  (add-model "/share/space1/kiselgra/sportscar/out26.obj" :type :subdobj)
  (add-model "/share/space1/kiselgra/sportscar/out31.obj" :type :subdobj)
  (add-model "/share/space1/kiselgra/sportscar/out24.obj" :type :subdobj)
	(subd-tess 2 1)
	(dof-config 0 60 5)
	(path-samples 64)
	(path-length 10)
	(light-samples 1) 
  )
