#ifndef __GI_UTIL_H__ 
#define __GI_UTIL_H__ 

/*! \file util.h
 * 	\brief general utilities for gi algorithms.
 * 	\note will also be included in cuda source. take care.
 */

#include <librta/cuda-kernels.h>
#include <librta/cuda-vec.h>

namespace gi {

	float halton(int index, int base);

	namespace cuda {

		struct halton_pool2f {
			float2 *data;
			int N;
		};

		/*! \brief Generates N float2 values generated by halton (2,3). 
		 *  \note The pointer in the returned structure points to gpu memory.
		 */
		halton_pool2f generate_halton_pool_on_gpu(int N);

	}
}

#endif

